### ISSUE TITLE
Live demo endpoint not working

### ISSUE THREAD

**Issue by rahulsalgare** [talkpython/eve-building-restful-mongodb-backed-apis-course#1]
I am following this tutorial series.
Found that live demo endpoint is not working.
Tried with: 
`https://eve-demo.herokuapp.com/people`

also tried:
`http://myapi/people`

**Comment by nicolaiarocci** [comment]
Hi @rahulsalgare. Heroku has just recently dropped support for the free Cedar instances (the type on which the eve-demo app was running). So yes, unfortunately, the endpoint which has been running for years is not working anymore. You can still install and run the demo app on your local server (you'll find the eve-demo repository in the pyeve organization here on GitHub).

**Comment by rahulsalgare** [comment]
Okay Thank you @nicolaiarocci.
